# IMPORT

In [1]:
try:
    import google.colab # type: ignore
    colab = True
except:
    colab = False

if colab:
    !git clone "https://github.com/cybernetic-m/eai-project.git" # type: ignore

In [2]:
# Model
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch import optim
from torch.optim.lr_scheduler import ExponentialLR 

# Others
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import json
 
# Our files
if colab:
    sys.path.append('/content/eai-project/training')
    sys.path.append('/content/eai-project/preprocessing')
    sys.path.append('/content/eai-project/dataset')
    sys.path.append('/content/eai-project/utils')
    sys.path.append('/content/eai-project/models')
    sys.path.append('/content/eai-project/testing')
    from train import train
    from preprocessing import *
    from thermal_dataset import thermal_dataset 
    from utils import *
    from complete_model import complete_model 
    from lstm_only import lstm_only
    from testing import test
    prefix = '/content'
        
else:
    from training.train import train
    from preprocessing.preprocessing import *
    from dataset.thermal_dataset import thermal_dataset
    from utils.csv_utils import *
    from models.complete_model import complete_model
    from models.lstm_only import lstm_only
    from testing.test import test
    prefix = '.'
    
pd.set_option('display.max_columns', None)

In [3]:
hyper_parameters = {'num_epochs': 30,
                    'batch_size': 256,
                    'hidden_dim' : 3,
                    'lr': 0.000001,
                    'mode': 'auto-weighted', #average, mlp, linear, auto-weighted
                    'extractor_type': 'lstm', #lstm, rnn
                    'ensemble': True,
                    'timesteps': 170,
                    'window_size':25,
                    'norm':True,
                    'file':1
                        }

ensemble_model = {'mlp': [{'layer_dim_list': [3,4,3]}],  
              'ARIMA': [{'p': 2, 'd': 0, 'q': 2, 'ps': 0, 'ds': 0, 'qs': 0, 's': 1}],
              'linear_regressor': [{'in_features': 3, 'out_features': 3}]
              }

ensemble_model1 = { 
              'ARIMA': [{'p': 2, 'd': 0, 'q': 2, 'ps': 0, 'ds': 0, 'qs': 0, 's': 1}],
              'linear_regressor': [{'in_features': 3, 'out_features': 3}, {'in_features': 3, 'out_features': 3}]
              }

ensemble_model2 = {
              'mlp': [{'layer_dim_list': [3,4,3]}],  
              'linear_regressor': [{'in_features': 3, 'out_features': 3}, {'in_features': 3, 'out_features': 3}]
              }

In [4]:
skip = False
test_flag = True
#if os.path.exists(prefix+'/X'+str(hyper_parameters['window_size'])+'testing'+str(hyper_parameters['file'])+str(hyper_parameters['norm'])+'.npy') and os.path.exists(prefix+'/X'+str(hyper_parameters['window_size'])+'training'+str(hyper_parameters['file'])+str(hyper_parameters['norm'])+'.npy'):
#    skip = True

**Reproducibility and Device Setting**

In [5]:
# Set a seed for reproducibility purposes
seed = 46
torch.manual_seed(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(seed)

# Set the device (cuda for Nvidia GPUs, mps for M1, M2 .. Apple Silicon)
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

# DATASET

In [6]:
link_zipped_csv = 'https://drive.google.com/file/d/1MssQF4pI_rZqiiDBP4XaLTT1ZaN6ykLm/view?usp=drive_link'
gdrive_link = 'https://drive.google.com/uc?id='
csv_dir = './csv'
zipped_file = './csv.zip'

download_csv(
    link_zipped_csv,
    gdrive_link,
    zipped_file
)

unzip_csv(
    zipped_file,
    csv_dir,
)


CSV file already downloaded!
CSV file already unzipped!


In [7]:
if not skip:

    path = '/content/csv/thermal_drift_features_lab_05_02.csv'

    # Read all the CSV files containing the Temperatures
    features_1 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_features_lab_05_02.csv'))
    features_2 = pd.read_csv(os.path.join(prefix, 'csv/thermal_drift_features_lab_05_03.csv'))
    features_3 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_features_lab_05_04.csv'))
    features_4 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_features_lab_05_05.csv'))
    features_5 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_features_lab_05_06.csv'))

    # Read all the CSV files containing the X1, Y1, Z1 
    targets_1 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_targets_lab_05_02.csv'))
    targets_2 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_targets_lab_05_03.csv'))
    targets_3 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_targets_lab_05_04.csv'))
    targets_4 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_targets_lab_05_05.csv'))
    targets_5 = pd.read_csv(os.path.join(prefix,'csv/thermal_drift_targets_lab_05_06.csv'))
    
    # Normalized columns files for X1, Y1, Z1 for the plot
    targets_norm_1= normalize_columns(targets_1, ['X1','Y1','Z1'], -1, 1)
    targets_norm_2= normalize_columns(targets_2, ['X1','Y1','Z1'], -1, 1)
    targets_norm_3= normalize_columns(targets_3, ['X1','Y1','Z1'], -1, 1)
    targets_norm_4= normalize_columns(targets_4, ['X1','Y1','Z1'], -1, 1)
    targets_norm_5= normalize_columns(targets_5, ['X1','Y1','Z1'], -1, 1)
    
    features_norm_1= normalize_columns(features_1, ['Temp Sensor 1','Temp Sensor 2', 'Temp Sensor 3', 'Temp Sensor 4'], -1, 1)
    features_norm_2= normalize_columns(features_2, ['Temp Sensor 1','Temp Sensor 2', 'Temp Sensor 3', 'Temp Sensor 4'], -1, 1)
    features_norm_3= normalize_columns(features_3, ['Temp Sensor 1','Temp Sensor 2', 'Temp Sensor 3', 'Temp Sensor 4'], -1, 1)
    features_norm_4= normalize_columns(features_4, ['Temp Sensor 1','Temp Sensor 2', 'Temp Sensor 3', 'Temp Sensor 4'], -1, 1)
    features_norm_5= normalize_columns(features_5, ['Temp Sensor 1','Temp Sensor 2', 'Temp Sensor 3', 'Temp Sensor 4'], -1, 1)

    # Create a list of features and targets to use for the next drop
    if hyper_parameters['norm']:
        features = [features_norm_1, features_norm_2, features_norm_3, features_norm_4, features_norm_5]
        targets = [targets_norm_1,targets_norm_2,targets_norm_3,targets_norm_4,targets_norm_4]
    else:
        features = [features_1, features_2, features_3, features_4, features_5]
        targets = [targets_1,targets_2,targets_3,targets_4,targets_5]

In [8]:
if not skip:
    for feature, target in zip(features, targets):
        feature.drop([
            "name", "tags",
            "2\"Tray1 Vacuum Sensor", "2\"Tray2 Vacuum Sensor", "2\"Tray3 Vacuum Sensor",
            "Avg Oven Temperature", "Chuck Temp [Cdeg]", "Chuck Temp2 [Cdeg]",
            "Chuck1 Vacuum Sensor", "Contrast", "Device State",
            "Dispenser1 Pressure Sensor", "Machine Room Temp", "Main Air", "Main Vacuum",
            "Oven Temperature", "PE_Rx", "PE_Ry", "PE_Rz", "PE_X1", "PE_Y1", "PE_Z1",
            "PUT1 Flow Sensor", "PUT2 Flow Sensor1", "PUT2 Flow Sensor2",
            "PUT2 Flow Sensor3", "PUT2 Flow Sensor4", "PUT2 Flow Sensor5",
            "Photodiode", "Pixel Power", "Preciser1 Vacuum Sensor",
            "Tec FIB1 Holder", "Tec FIB1 Plate", "Tec FIB2 Holder", "Tec FIB2 Plate",
            "Torque11","Torque2","Torque3","Torque4","Torque5","Torque6"
        ], axis=1, inplace=True)
        if 'name' in target.keys() and 'tags' in target.keys():

            target.drop(['name', 'tags'], axis=1, inplace=True)


In [9]:
if not skip:
    print(features[1]) # Print the features_1 table

                        time  Temp Sensor 1  Temp Sensor 2  Temp Sensor 3  \
0        1714687200035019000       0.901639       0.627907       0.935484   
1        1714687200090637000       0.901639       0.627907       0.935484   
2        1714687200177338000       0.901639       0.627907       0.935484   
3        1714687200228517000       0.901639       0.627907       0.935484   
4        1714687200279903000       0.901639       0.627907       0.935484   
...                      ...            ...            ...            ...   
1248011  1714773599360645000       0.672131       0.674419       0.483871   
1248012  1714773599473292000       0.672131       0.674419       0.483871   
1248013  1714773599580569000       0.672131       0.674419       0.483871   
1248014  1714773599762038000       0.672131       0.674419       0.483871   
1248015  1714773599869383000       0.672131       0.674419       0.483871   

         Temp Sensor 4  
0             0.911765  
1             0.911765  


In [10]:
if not skip:

    print(targets[1]) # Print the target_1

                      time        X1        Y1        Z1
0      1714687207558354000  0.877249       NaN       NaN
1      1714687207564731000       NaN -0.876387       NaN
2      1714687207615696000       NaN       NaN  0.698630
3      1714687218845182000  0.870077       NaN       NaN
4      1714687218860796000       NaN -0.877755       NaN
...                    ...       ...       ...       ...
23104  1714773578301848000       NaN  0.955317       NaN
23105  1714773578313892000       NaN       NaN -0.287671
23106  1714773589691570000 -0.004000       NaN       NaN
23107  1714773589700556000       NaN  0.944901       NaN
23108  1714773589724371000       NaN       NaN -0.315068

[23109 rows x 4 columns]


In [11]:
if not skip:
    # Put X1, Y1, Z1 on the same row of X1 eliminating the NAN values
    fixed_targets = [] # Create a list of target in which we put X1, Y1, Z1 in the same row
    for target in targets:
        fixed_targets.append(transform_dataframe(target)) # iterate over target_1,2,3 ... and append in fixed_targets

In [12]:
if not skip:

    print(fixed_targets[1]) # Print the fixed_target_1

              time        X1        Y1        Z1
0     1.714687e+18  0.877249 -0.876387  0.698630
1     1.714687e+18  0.870077 -0.877755  0.726027
2     1.714687e+18  0.862210 -0.874809  0.753425
3     1.714687e+18  0.882294 -0.881475  0.753425
4     1.714687e+18  0.872267 -0.881519  0.726027
...            ...       ...       ...       ...
7698  1.714774e+18  0.031200  0.951937 -0.260274
7699  1.714774e+18  0.006015  0.966296 -0.287671
7700  1.714774e+18  0.023985  0.957713 -0.260274
7701  1.714774e+18  0.011520  0.955317 -0.287671
7702  1.714774e+18 -0.004000  0.944901 -0.315068

[7703 rows x 4 columns]


In [13]:
if not skip:
    # Merge of targets with features in one single dataframe
    complete_numbers_list = [] # List of the table with columns that are numbers (0,1,2..) in which we unify both features and targets merging on closest time row
    for fixed_target, feature in zip(fixed_targets, features):
        complete_numbers_list.append(merge_on_closest_time(fixed_target.reset_index(), feature.reset_index()))

    trainig_number_list = []
    testing_number_list = []
    for i in range(len(complete_numbers_list)):
        part_numbers_list = complete_numbers_list[:i] + complete_numbers_list[i+1:]
        trainig_number_list.append(pd.concat(part_numbers_list))
        testing_number_list.append(complete_numbers_list[i])
        
    complete_numbers_dataframe = pd.concat(complete_numbers_list)


In [14]:
if not skip: 
    print(complete_numbers_list) # Print of one example

[        0                             1         2         3         4   \
0        0 2024-05-02 09:00:01.106507008 -1.000000  0.736636  0.177570   
1        1 2024-05-02 09:00:12.382008064 -0.981332  0.687808  0.177570   
2        2 2024-05-02 09:00:23.632736000 -0.945775  0.688676  0.140187   
3        3 2024-05-02 09:00:34.970393088 -0.929981  0.667533  0.102804   
4        4 2024-05-02 09:00:46.143995904 -0.905817  0.700378  0.028037   
...    ...                           ...       ...       ...       ...   
4166  4166 2024-05-02 21:59:11.262568960 -0.121050 -0.919412 -0.906542   
4167  4167 2024-05-02 21:59:22.587275008 -0.129462 -0.926667 -0.981308   
4168  4168 2024-05-02 21:59:33.874593024 -0.164806 -0.904891 -0.962617   
4169  4169 2024-05-02 21:59:45.187085056 -0.131839 -0.894467 -0.962617   
4170  4170 2024-05-02 21:59:56.406018048 -0.117183 -0.916946 -0.981308   

          5                          6         7         8         9        10  
0          7 2024-05-02 09:00

In [15]:
if not skip:

    complete = complete_numbers_dataframe.rename(columns={
        0: 'id',
        1: 'time',
        2: 'X1',
        3: 'Y1',
        4: 'Z1',
        5: 'to_remove',
        6: 'time_2',
        7: 'Temp1',
        8: 'Temp2',
        9: 'Temp3',
        10: 'Temp4'
        })
    complete.drop(['time', 'to_remove', 'time_2'], axis=1, inplace=True)
    training_list = []
    testing_list = []
    for training, testing in zip(trainig_number_list, testing_number_list):
        training_tmp = training.rename(columns={
            0: 'id',
            1: 'time',
            2: 'X1',
            3: 'Y1',
            4: 'Z1',
            5: 'to_remove',
            6: 'time_2',
            7: 'Temp1',
            8: 'Temp2',
            9: 'Temp3',
            10: 'Temp4'
            })
        training_tmp.drop(['time', 'to_remove', 'time_2'], axis=1, inplace=True)
        training_list.append(training_tmp)
        
        testing_tmp = testing.rename(columns={
            0: 'id',
            1: 'time',
            2: 'X1',
            3: 'Y1',
            4: 'Z1',
            5: 'to_remove',
            6: 'time_2',
            7: 'Temp1',
            8: 'Temp2',
            9: 'Temp3',
            10: 'Temp4'
            })
        testing_tmp.drop(['time', 'to_remove', 'time_2'], axis=1, inplace=True)
        testing_list.append(testing_tmp)

In [16]:
if not skip:

    print(training_list)

[        id        X1        Y1        Z1     Temp1     Temp2     Temp3  \
0        0  0.877249 -0.876387  0.698630  0.868852  0.558140  0.935484   
1        1  0.870077 -0.877755  0.726027  0.868852  0.441860  0.967742   
2        2  0.862210 -0.874809  0.753425  0.868852  0.465116  1.000000   
3        3  0.882294 -0.881475  0.753425  0.868852  0.534884  0.967742   
4        4  0.872267 -0.881519  0.726027  0.868852  0.558140  0.967742   
...    ...       ...       ...       ...       ...       ...       ...   
7705  7705  0.133007 -0.331885  0.522388  0.470588  0.285714  0.703704   
7706  7706  0.148633 -0.334070  0.582090  0.470588  0.285714  0.703704   
7707  7707  0.177016 -0.346153  0.582090  0.470588  0.285714  0.703704   
7708  7708  0.116749 -0.339384  0.552239  0.470588  0.285714  0.703704   
7709  7709  0.111034 -0.374823  0.552239  0.470588  0.285714  0.703704   

         Temp4  
0     0.970588  
1     0.941176  
2     0.911765  
3     0.941176  
4     0.941176  
...     

In [18]:
if not skip:
    '''
    complete.astype(float)

    X = complete[['Temp1','Temp2', 'Temp3', 'Temp4']]
    Y = complete[['X1', 'Y1', 'Z1']]

    Y = Y.values.astype(np.float32)
    Y = my_gradient(Y, window_size=hyper_parameters['window_size'])
    
     
    X = X.values.astype(np.float32)
    X /= 100
    X = X[len(X):20]
    '''
    print(hyper_parameters['window_size'])
    # Save the features and targets in file npy
    #np.save(prefix+'/X'+str(hyper_parameters['window_size'])+'.npy',X)
    #np.save(prefix+'/Y'+str(hyper_parameters['window_size'])+'.npy',Y)
    for i, (testing, training) in enumerate(zip(testing_list, training_list)):
        trainingx = normalize_columns(training, ['Temp1','Temp2', 'Temp3', 'Temp4'],-1,1)
        trainingy = normalize_columns(training, ['X1', 'Y1', 'Z1'],-1,1)
        training.astype(float)
        #print(training)
        X = trainingx[['Temp1','Temp2', 'Temp3', 'Temp4']]
        Y = trainingy[['X1', 'Y1', 'Z1']]
        
        Y = Y.values.astype(np.float32)
        Y = my_gradient(Y, window_size=hyper_parameters['window_size'])
        Y = normalize_array(Y,-1,1)
        
        X = X.values.astype(np.float32)
        print('training'+str(i))
        print('X',len(X))
        print(np.max(X))
        print('Y',len(Y))
        print(np.max(Y))
        # Save the features and targets in file npy
        np.save(prefix+'/X'+str(hyper_parameters['window_size'])+'training'+str(i)+str(hyper_parameters['norm'])+'.npy',X)
        np.save(prefix+'/Y'+str(hyper_parameters['window_size'])+'training'+str(i)+str(hyper_parameters['norm'])+'.npy',Y)
        testingx = normalize_columns(testing, ['Temp1','Temp2', 'Temp3', 'Temp4'],-1,1)
        testingy = normalize_columns(testing, ['X1', 'Y1', 'Z1'],-1,1)
        testing.astype(float)

        X = testingx[['Temp1','Temp2', 'Temp3', 'Temp4']]
        Y = testingy[['X1', 'Y1', 'Z1']]

        Y = Y.values.astype(np.float32)
        Y = my_gradient(Y, window_size=hyper_parameters['window_size'])
        Y = normalize_array(Y,-1,1)
        
        X = X.values.astype(np.float32)
        print('testing'+str(i))
        print('X',len(X))
        print(np.max(X))
        print('Y',len(Y))
        print(np.max(Y))     
        # Save the features and targets in file npy
        np.save(prefix+'/X'+str(hyper_parameters['window_size'])+'testing'+str(i)+str(hyper_parameters['norm'])+'.npy',X)
        np.save(prefix+'/Y'+str(hyper_parameters['window_size'])+'testing'+str(i)+str(hyper_parameters['norm'])+'.npy',Y)


25
error
error
errors: 0
training0
X 30829
1.0
Y 30804
1.0
errors: 0
testing0
X 4171
1.0
Y 4146
1.0
error
error
errors: 0
training1
X 27297
1.0
Y 27272
1.0
errors: 0
testing1
X 7703
1.0
Y 7678
1.0
errors: 0
training2
X 27294
1.0
Y 27269
1.0
error
error
errors: 0
testing2
X 7706
1.0
Y 7681
1.0
error
error
errors: 0
training3
X 27290
1.0
Y 27265
1.0
errors: 0
testing3
X 7710
1.0
Y 7685
1.0
error
error
errors: 0
training4
X 27290
1.0
Y 27265
1.0
errors: 0
testing4
X 7710
-1.0
Y 7685
1.0


In [ ]:
if not skip:

    targets_norm_1['time'] = pd.to_datetime(targets_norm_1['time'], unit='ns')

    # Reshape the DataFrame using melt()
    targets_melted = targets_norm_1.reset_index().melt(id_vars=['time'], value_vars=['X1', 'Y1', 'Z1'], var_name='variable', value_name='value')

    # Drop rows where 'value' is NaN (to keep only the non-null entries)
    targets_melted = targets_melted.dropna(subset=['value'])

    # Plot the data
    plt.figure(figsize=(10, 6))
    for var in targets_melted['variable'].unique():
        # Filter data for each variable and plot
        temp_df = targets_melted[targets_melted['variable'] == var]
        plt.plot(temp_df['time'], temp_df['value'], label=var)

    # Add labels and title
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.title('Plot of X1, Y1, Z1 over Time')
    plt.legend(title='Variable')

    # Show the plot
    plt.show()

    #targets.plot(y='X1',x='time')

In [ ]:
if not skip:

    # Convert 'time' to datetime (nanoseconds to datetime)
    features_1['time'] = pd.to_datetime(features_1['time'], unit='ns')

    # Set 'time' as the index
    features_1.set_index('time', inplace=True)

    # Optionally, you can plot X1, Y1, Z1 directly
    features_1[['Temp Sensor 1', 'Temp Sensor 2', 'Temp Sensor 3', 'Temp Sensor 4', ]].plot()

    # Add labels and title
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.title('Plot of Temp Sensor 1, Temp Sensor 2, Temp Sensor 3, Temp Sensor 4 over Time')

    # Show the plot
    plt.show()

In [ ]:
if skip:
    # If skip is true, we simply load the data 
    X = np.load(prefix+'/X'+str(hyper_parameters['window_size'])+'training'+str(hyper_parameters['file'])+'.npy')
    Y = np.load(prefix+'/Y'+str(hyper_parameters['window_size'])+'training'+str(hyper_parameters['file'])+'.npy')

print(X)
print(Y)

splitPerc = [0.7,0.3]
splitted_X = split(X, splitPerc)
splitted_Y = split(Y, splitPerc)

[[21.36 21.64 21.63 21.59]
 [21.36 21.7  21.62 21.6 ]
 [21.36 21.76 21.63 21.6 ]
 ...
 [21.23 21.65 21.49 21.47]
 [21.23 21.64 21.49 21.46]
 [21.21 21.64 21.48 21.47]]
[[0.00509315 0.00554387 0.0203726 ]
 [0.00384014 0.00700421 0.02241587]
 [0.0026893  0.0071845  0.02394832]
 ...
 [0.00345252 0.00874099 0.00426683]
 [0.0033774  0.00869291 0.00363582]
 [0.0034976  0.00853365 0.00366587]]
0
15866
0
15863


In [ ]:
for i in [15, 20, 25]:
    X = np.load(prefix+'/X'+str(i)+'.npy')
    Y = np.load(prefix+'/Y'+str(i)+'.npy')

    print(X)
    print(Y)

[[21.41 21.69 21.67 21.64]
 [21.4  21.7  21.67 21.64]
 [21.42 21.71 21.68 21.65]
 ...
 [21.25 21.74 21.51 21.48]
 [21.25 21.72 21.5  21.5 ]
 [21.25 21.72 21.51 21.48]]
[[0.0109096  0.00178571 0.01841518]
 [0.0094029  0.00831473 0.02371652]
 [0.00742188 0.01023996 0.03111049]
 ...
 [0.0024135  0.01208147 0.00613839]
 [0.00186942 0.01131417 0.00683594]
 [0.00239955 0.00983538 0.00739397]]
[[21.41 21.69 21.67 21.64]
 [21.4  21.7  21.67 21.64]
 [21.42 21.71 21.68 21.65]
 ...
 [21.25 21.74 21.51 21.48]
 [21.25 21.72 21.5  21.5 ]
 [21.25 21.72 21.51 21.48]]
[[0.0082883  0.0054012  0.02091165]
 [0.00666706 0.00697838 0.02558153]
 [0.0047433  0.00777138 0.02884164]
 ...
 [0.00366248 0.01060268 0.00273144]
 [0.0036008  0.01049401 0.00252585]
 [0.00390919 0.01013863 0.00343633]]
[[21.41 21.69 21.67 21.64]
 [21.4  21.7  21.67 21.64]
 [21.42 21.71 21.68 21.65]
 ...
 [21.25 21.74 21.51 21.48]
 [21.25 21.72 21.5  21.5 ]
 [21.25 21.72 21.51 21.48]]
[[0.00509315 0.00554387 0.0203726 ]
 [0.00384014 0.0

# MODEL

In [ ]:

#1 ARIMA 2 linear
#1 MLP 2 linear
#
#tutti i voting

In [ ]:
datasetTrain = thermal_dataset((splitted_X[0],splitted_Y[0]), hyper_parameters['timesteps'], device)
datasetVal = thermal_dataset((splitted_X[1],splitted_Y[1]), hyper_parameters['timesteps'], device)


In [ ]:
# Training, Test and Validation Dataloader initialization
loaderTrain = DataLoader(datasetTrain, shuffle=True, batch_size=hyper_parameters['batch_size'])
loaderVal = DataLoader(datasetVal, shuffle=True, batch_size=hyper_parameters['batch_size'])

# Model Initialization (True if you want to use the Ensemble model, False in you want to use a single LSTM model)
if hyper_parameters['ensemble'] == False:
    model = lstm_only(hidden_dim=hyper_parameters['hidden_dim'], timesteps=hyper_parameters['timesteps'] ,input_dim=4, output_dim=3).to(device)
elif hyper_parameters['ensemble'] == True:  
    model = complete_model(hidden_dim=hyper_parameters['hidden_dim'], input_dim=4, model_dict=ensemble_model, device=device, mode=hyper_parameters['mode'], extractor_type=hyper_parameters['extractor_type']).to(device)

# Definition of the optimizer and loss function

if hyper_parameters['ensemble'] == False:
    optimizer = optim.Adam(model.parameters(), lr=hyper_parameters['lr'])
elif hyper_parameters['ensemble'] == True:
    optimizer = []
    models, arima, rnn =model.get_models()
    optimizer += [optim.Adam(model.parameters(), lr=hyper_parameters['lr']) for model in models]
    optimizer += [optim.Adam(model.parameters(), lr=hyper_parameters['lr']) for model in arima]
    optimizer += [optim.Adam(model.parameters(), lr=hyper_parameters['lr']) for model in rnn]



loss_fn = nn.MSELoss()
scheduler = ExponentialLR(optimizer, gamma=0.9)
model

3
Ensemble Model Summary: ModuleList(
  (0): mlp(
    (linear_layers): ModuleList(
      (0): Linear(in_features=3, out_features=4, bias=True)
      (1): Linear(in_features=4, out_features=3, bias=True)
    )
  )
  (1): linear(
    (linear_layer): Linear(in_features=3, out_features=3, bias=False)
  )
) ModuleList(
  (0): ARIMA(
    (PD): TwoPolynomialOperation(
      (first_poly): BiasOnePolynomial()
      (second_poly): Polynomial()
    )
    (Q): BiasOnePolynomial()
    (PDS): TwoPolynomialOperation(
      (first_poly): BiasOnePolynomial()
      (second_poly): Polynomial()
    )
    (QS): BiasOnePolynomial()
  )
) ModuleList()


TypeError: list is not an Optimizer

In [ ]:

train(
    num_epochs=hyper_parameters['num_epochs'],
    loss_fn=loss_fn,
    model=model,
    optimizer=optimizer,
    scheduler=scheduler,
    training_dataloader=loaderTrain,
    validation_dataloader=loaderVal,
    hyperparams=hyper_parameters,
    model_dict = ensemble_model,
    complete=hyper_parameters['ensemble']
)


# Test

In [ ]:
# Need to specify a model.pt file to load! In the directory results that you want to test
result_path = '/results/training_2025-01-31_10-13' 
model_path = prefix + result_path +'/model.pt'

# Read hyperparameters
with open (prefix + result_path + '/hyperparam.json', 'r') as f:
    hyperparams = json.load(f)
    
X = np.load(prefix+'/X'+str(hyper_parameters['window_size'])+'testing'+str(hyper_parameters['file'])+'.npy')
Y = np.load(prefix+'/X'+str(hyper_parameters['window_size'])+'testing'+str(hyper_parameters['file'])+'.npy')

datasetTest = thermal_dataset((X,Y), hyperparams['timesteps'], device)
loaderTest = DataLoader(datasetTest, shuffle=True, batch_size=hyperparams['batch_size'])
# Section in which we reinitialize the model for testing depending on the hyperparameters.json and ensemble.json (if present) in the directories of results
# Read Ensemble models data (if complete = True)
if hyperparams['ensemble'] == True:
    # Read Ensemble model parameters and initialize the model
    with open (prefix + result_path + '/ensemble.json', 'r') as f:
        model_dict = json.load(f)
    model = complete_model(hidden_dim=hyperparams['hidden_dim'], input_dim=4, model_dict=model_dict, device=device, mode=hyperparams['mode'], extractor_type=hyperparams['extractor_type']).to(device)
# Otherwise create an LSTM only model
else:
    model = lstm_only(hidden_dim=hyperparams['hidden_dim'], timesteps=hyperparams['timesteps'] ,input_dim=4, output_dim=3).to(device)

if test_flag:
    test_metrics, test_loss_avg, total_inference_time, inference_time_avg, y_true_list, y_pred_list = test(
        model=model,
        model_path=model_path,
        test_dataloader=loaderTest,
        loss_fn=loss_fn,
        complete=hyperparams['ensemble']
    )
print("Test metrics:")
print(f"rmse: {test_metrics['rmse']} , mae: {test_metrics['mae']}, r2: {test_metrics['r2']}")
print("Others:")
print(f"Average Loss: {test_loss_avg}, Total Inference Time (All Dataset): {total_inference_time}, Average Inference Time: {inference_time_avg}")


In [ ]:
path = prefix + result_path  # type ./results/ensemble_batch_256

# Load the dictionaries
with open (path + '/train_metrics.json', 'r') as f:
    train_metrics = json.load(f)
with open (path + '/valid_metrics.json', 'r') as f:
    valid_metrics = json.load(f)

# Initialize a list of epochs [1,2,3, ...] for the plots x-axis
epochs = [i for i in range(1, hyper_parameters['num_epochs']+1)]

# Compute training loss as the square of rmse for each element because loss = mse
# Both for training and validation
training_loss = [rmse**2 for rmse in train_metrics['rmse']] 
valid_loss = [rmse**2 for rmse in valid_metrics['rmse']] 

plt.plot(epochs, training_loss, label='Training', color='b')
plt.plot(epochs, valid_loss, label='Validation', color='r')
plt.title('Loss (RMSE^2)')
plt.xlabel('Epochs')
plt.ylabel('Loss value')
plt.legend()

plt.tight_layout()  # This helps to prevent overlapping of subplots
plt.savefig(path+'/loss')  # Save the figure to the specified path
plt.show()

In [ ]:
path = prefix + result_path  # type ./results/ensemble_batch_256

# Load the dictionaries
with open (path + '/train_metrics.json', 'r') as f:
    train_metrics = json.load(f)
with open (path + '/valid_metrics.json', 'r') as f:
    valid_metrics = json.load(f)

# Initialize a list of epochs [1,2,3, ...] for the plots x-axis
epochs = [i for i in range(1, hyper_parameters['num_epochs']+1)]

plt.plot(epochs, train_metrics['mae'], label='Training', color='b')
plt.plot(epochs, valid_metrics['mae'], label='Validation', color='r')
plt.title('Mean Absolute Error')
plt.xlabel('Epochs')
plt.ylabel('MAE value')
plt.legend()

plt.tight_layout()  # This helps to prevent overlapping of subplots
plt.savefig(path + '/mae')  # Save the figure to the specified path
plt.show()

In [ ]:
path = prefix + result_path  # type ./results/ensemble_batch_256

# Load the dictionaries
with open (path + '/train_metrics.json', 'r') as f:
    train_metrics = json.load(f)
with open (path + '/valid_metrics.json', 'r') as f:
    valid_metrics = json.load(f)

# Initialize a list of epochs [1,2,3, ...] for the plots x-axis
epochs = [i for i in range(1, hyper_parameters['num_epochs']+1)]

plt.plot(epochs, train_metrics['r2'], label='Training', color='b')
plt.plot(epochs, valid_metrics['r2'], label='Validation', color='r')
plt.title('R2 (Coefficient of determination)')
plt.xlabel('Epochs')
plt.ylabel('R2 value')
plt.legend()

plt.tight_layout()  # This helps to prevent overlapping of subplots
plt.savefig(path + '/r2')  # Save the figure to the specified path
plt.show()

In [ ]:
# Create the lists of X1, Y1, Z1 true values to plot
x1_true = [x[0] for x in y_true_list]
y1_true = [y[1] for y in y_true_list]
z1_true = [z[2] for z in y_true_list]

# Create the lists of X1, Y1, Z1 predicted values to plot
x1_pred = [x[0] for x in y_pred_list]
y1_pred = [y[1] for y in y_pred_list]
z1_pred = [z[2] for z in y_pred_list]

# Create x-axis
t = [i for i in range(1, len(y_pred_list)+1)]


In [ ]:
# Initialize a list of epochs [1,2,3, ...] for the plots x-axis
#t = [i for i in range(1, len(Y[:,0])+1)]
plt.plot(t, y1_true, label='Ground Truth', color='b')
plt.plot(t, x1_pred, label='Prediction', color='r')
plt.title('X1 Sequence')
plt.xlabel('Time')
plt.ylabel('X1')
plt.legend()

plt.tight_layout()  # This helps to prevent overlapping of subplots
#plt.savefig(path + '/r2')  # Save the figure to the specified path
plt.show()

In [ ]:
# Initialize a list of epochs [1,2,3, ...] for the plots x-axis

plt.plot(t[:100], y1_true[:100], label='Ground Truth', color='b')
plt.plot(t[:100], y1_pred[:100], label='Prediction', color='r')
plt.title('Y1 Sequence')
plt.xlabel('Time')
plt.ylabel('Y1')
plt.legend()

plt.tight_layout()  # This helps to prevent overlapping of subplots
#plt.savefig(path + '/r2')  # Save the figure to the specified path
plt.show()

In [ ]:
# Initialize a list of epochs [1,2,3, ...] for the plots x-axis

plt.plot(t, z1_true, label='Ground Truth', color='b')
plt.plot(t, z1_pred, label='Prediction', color='r')
plt.title('Z1 Sequence')
plt.xlabel('Time')
plt.ylabel('Z1')
plt.legend()

plt.tight_layout()  # This helps to prevent overlapping of subplots
#plt.savefig(path + '/r2')  # Save the figure to the specified path
plt.show()